include: package:effective_dart/analysis_options.1.2.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
