name: durations
description: How long has it been?
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_redurx: ^1.1.1
  equatable: ^1.0.0
  meta: ^1.1.7
  path: ^1.6.4
  path_provider: ^1.4.5
  quiver: ^2.0.5
  sembast: ^2.1.1
  sprintf: ^4.0.0
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.1.0
  mockito: ^4.1.1
  test: ^1.5.1

flutter:
  uses-material-design: true
