name: durations
description: How long has it been?
version: 1.0.0+1

environment:
  sdk: ^2.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_linkify: ^3.1.0
  flutter_localizations:
    sdk: flutter
  flutter_redurx: ^1.1.1
  charts_flutter: ^0.8.1
  csv: ^4.0.3
  equatable: ^1.0.2
  intl: ^0.16.0
  meta: ^1.1.8
  more: ^2.2.0
  package_info: ^0.4.0+13
  path: ^1.6.4
  path_provider: ^1.5.1
  quiver: ^2.0.5
  sembast: ^2.1.2
  share:
    git:
      url: https://github.com/pboos/plugins.git
      path: packages/share
      ref: feature/shareFile
  sprintf: ^4.0.2
  url_launcher: ^5.4.1
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  effective_dart: ^1.2.1
  mockito: ^4.1.1
  test: ^1.9.4

flutter:
  assets:
    - assets/launcher/icon.png
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
